on:
  push:

jobs:
  test_unit:
    runs-on: ubuntu-22.04
    container:
      image: node:18-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Unit tests
        run: npm run test:unit
