on:
  push:

jobs:
  test_unit:
    runs-on: ubuntu-22.04
    container:
      image: node:18-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Unit tests
        run: npm run test:unit
  test_func:
    runs-on: ubuntu-22.04
    container:
      image: docker:dind
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run depedencies
        run: docker-compose -f tests/functionnal/dependencies/docker-compose.yaml up -d
      - name: Functionnal testing
        run: docker-compose -f tests/functionnal/dependencies/tester-compose.yaml up --abort-on-container-exit --exit-code-from tester
      - name: Clean containers
        run: docker-compose -f tests/functionnal/dependencies/docker-compose.yaml down
  test_integ:
    runs-on: ubuntu-22.04
    container:
      image: docker:dind
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run depedencies
        run: docker-compose -f tests/integ/dependencies/docker-compose.yaml up -d
      - name: Integration testing
        run: docker-compose -f tests/integ/dependencies/tester-compose.yaml up --abort-on-container-exit --exit-code-from tester
      - name: Clean containers
        run: docker-compose -f tests/integ/dependencies/docker-compose.yaml down
