on:
  push:
    branches:
      - main

jobs:
  test-unit:
    name: test-unit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Unit tests
        run: npm run test:unit
